version: "3.3"
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:4.0.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:4.0.0
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  rest-proxy:
    image: confluentinc/cp-kafka-rest
    links:
      - kafka
    ports:
      - "8082:8082"
    environment:
      KAFKAREST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      KAFKAREST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKAREST_HOST_NAME: localhost
